Remove EmailPreviewTemplate
alphagov/notifications-utils pull request #1159
Opened 2024-10-25 11:00 UTC by quis

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        (EmailPreviewTemplate, "email", 'style="word-wrap: break-word; color: #1D70B8;"'),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR797

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        EmailPreviewTemplate,
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR498-R507

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        (EmailPreviewTemplate, "email", {}),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR510-R532

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        (EmailPreviewTemplate, "email", {}),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR815-R828

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        ),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR535-R583

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        EmailPreviewTemplate,
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR883-R899

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        ),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR603-R631

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -    assert "Example service" in str(template)
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR902-R914

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -    assert '&lt;script&gt;alert("")&lt;/script&gt;' in str(template)
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR917-R922

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -    assert "test@example.com" in str(template)
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR925-R941

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -    assert expected_content in str(template)
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR944-R959

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        (EmailPreviewTemplate, "email", {}),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR976-R979 (with number just under limit 👍🏻 )

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        (EmailPreviewTemplate, "email", {}),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR962-R966

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        (EmailPreviewTemplate, "email", {}),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR969-R973

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        (EmailPreviewTemplate, "email", {}),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR982-R996

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        EmailPreviewTemplate,
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR999-R1006

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        ),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR1009-R1051

2024-10-25 11:49 UTC, quis commented on tests/test_template_types.py
> -        ),
https://github.com/alphagov/notifications-admin/pull/5266/files#diff-e7949c604d3f8a5b6bc46af2528b92206f955af09f02fecb5086b004c00041abR1054-R1080

2024-10-25 15:43 UTC, tombye requested changes
This all looks good to go (thanks for the really helpful comments on the changes to the tests).

Think it needs a version bump and changelog entry, then good to go 👍🏻

2024-10-25 16:02 UTC, quis commented
@tombye  Version bump and changelog done

2024-10-29 09:54 UTC, tombye approved these changes
Thanks for making the changes @quis. Now looks good to go 👍🏻

2024-10-29 10:08 UTC, tombye approved these changes
2nd approval as changes since created merge conflicts (now resolved) 👍🏻

2024-10-29 10:16 UTC, merged